
export const CREATOR_DATA_FOUND = "CREATOR_DATA_FOUND";
export const CREATOR_NOT_FOUND = "CREATOR_NOT_FOUND";
export const DASHBOARD_ERROR = "DASHBOARD_ERROR";
export const DASHBOARD_LOADING = "DASHBOARD_LOADING";